#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e
cd "$(dirname "$0")/.."


script/bootstrap
script/-check-docker-compose

echo
echo "==> Rebuilding containers…"
docker-compose -f docker-compose-dash.yml up -d --build
